# -*- coding: utf-8 -*-
"""Mini Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmHJRXCyxRD5P9bBy-5iuK4k0X4okfyF

# ชุดที่ 1 Gym Members Exercise Dataset

ได้ทำการลดข้อมูล บางส่วนที่มีช่องว่าง

เหตุผลเพราะว่าข้อมูล ถ้าใส่ 0 อาจจะทำให้ ข้อมูลที่มีชื่อโดนใส่ด้วย
"""

import pandas as pd  # อ่านไฟล์ และแก้ไขไฟล์

dataGym = "gym_members_exercise_tracking.csv"                                             #เรียกไฟล์
data = pd.read_csv(dataGym)                                                                        #อ่านไฟล์

print("\033[31mประเภทข้อมูลและจำนวนข้อมูล\033[33m")
data.info()                        #ดูประเภทข้อมูล จำนวนข้อมูลทั้งหมด
print("\033[0m\n _________________________________________________ \n")

print("\033[31mข้อมูลที่มีข่องว่าง\033[34m")
print(data.isnull().sum())  #เช็คข้อมูลที่หายไปทั้งหมด
data.dropna(inplace=True)   # ลบแถวข้อมูลที่หายไป
print("\033[0m\n _________________________________________________ \n")

print("\033[31mNew ประเภทข้อมูลและจำนวนข้อมูล\033[33m")
data.info()                        #ดูประเภทข้อมูล จำนวนข้อมูลทั้งหมด  อีกรอบ
print("\033[0m\n _________________________________________________ \n")

print("\033[31mNew ข้อมูลที่มีข่องว่าง\033[34m")
print(data.isnull().sum())     #เช็คข้อมูลที่หายไปทั้งหมด อีกรอบ
print("\033[0m\n _________________________________________________ \n")

print("\033[31mไม่มีข้อมูลที่ซ้ำกัน\033[0m")
print(data.duplicated().sum())  #เช็คข้อมูลที่ซ้ำกันทั้งหมด

data.to_csv('cleandataGym',index=False)    #seveไฟล์งาน

"""# Machine Learning Supervised - Decision Tree

**โจทย์เกี่ยวกับการออกกำลังกาย**

ข้อมูลของนายสมมาย อายุ 36 ปี เพศชาย ชีพจรสูงสุด 174 ระยะเวลาในการออกกำลังกาย 1.59 ชม

%ไขมันในร่างกาย 21.3 ความถี่ในการออกกำลังกาย 3วัน/สัปดาห์  

* จงหาว่า ประเภทของการออกกำลังกายของนายสมมายคือประเภทใด ?
"""

import pandas as pd # อ่านไฟล์ และแก้ไขข้อมูล

from sklearn.tree import DecisionTreeClassifier  # สำหรับสร้าง Decision Tree Classifier

from sklearn import tree  # สำหรับการแสดงผลของ Decision Tree
import matplotlib.pyplot as plt  # สำหรับการสร้างกราฟและภาพ

dataGym = "/content/cleandataGym"                                                                  #เรียกไฟล์
data = pd.read_csv(dataGym)                                                                        #อ่านไฟล์

print("\033[31mประเภทข้อมูลและจำนวนข้อมูล\033[33m")
data.info()  #ดูประเภทข้อมูล จำนวนข้อมูลทั้งหมด
print("\033[0m\n _________________________________________________ \n")

# X เลือกข้อมูลที่ต้องการทำ โมเดล
X = data[['Age', 'Gender', 'Max_BPM', 'Session_Duration (hours)', 'Fat_Percentage', 'Workout_Frequency (days/week)']]
Y = data['Workout_Type'] #เป้าหมายที่ต้องการทำนาย

X.loc[:,'Gender'] = X['Gender'].map({'Male': 0, 'Female': 1}) # แปลงข้อมูล 'Gender' จากคำเป็นตัวเลข (0 = ชาย, 1 = หญิง)

Tree = DecisionTreeClassifier(max_depth=2) # สร้างโมเดล Decision Tree Classifier   ความลึก 3

Tree.fit(X,Y)  # ฝึกโมเดล กฏตัดสินใจ

# ทำนายข้อมูลใหม่
New = pd.DataFrame([[36, 0, 174, 1.59, 21.3, 3]], columns=X.columns)    #สร้างข้อมูลใหม่ที่ต้องการทำนาย ในคอลัมน์
print("\033[31m ประเภทของนายสมมาย \033[33m")
print(  Tree.predict(New))                       # ข้อมูลใหม่ที่ทำนาย จาก x แสดงออกเป็น  y ทางหน้าจอ

plt.figure(figsize=(15,10))  # สร้างหน้าต่างกราฟใหม่ ก  ส นิ้ว
tree.plot_tree(Tree, feature_names=X.columns, class_names=Y.unique(), filled=True)  #แสดงต้นไม้
plt.show()  #แสดงกราฟบนหน้าจอ

"""# Machine Learning Unsupervised - Clustering

**การแบ่งกลุ่มการเผาผลาญแคลรี่เพศชายและเพศหญิง**

* เพศชายและเพศหญิงมีลักษณะเผาผลาญแคลรี่ที่แตกต่างกันหรือไม่?
"""

import pandas as pd # อ่านไฟล์ และแก้ไขข้อมูล
from sklearn.cluster import KMeans   #การทำทำนายค่า ที่มีข้อมูลมาก
import matplotlib.pyplot as plt  # สำหรับการสร้างกราฟและภาพ

dataGym = "/content/cleandataGym"                                                                                                                #ดาวโหลดไฟล์
data = pd.read_csv(dataGym)                                                                                                                      #อ่านไฟล์

X = data[['Calories_Burned' , 'Session_Duration (hours)']].values #หาข้อมูล Datafame .values 2 D array

kmeans = KMeans(n_clusters=2)    #แบ่งข้อมูลเป็น 2 กลุ่ม โดยหาจุดกลางกลุ่ม
Kmean= kmeans.fit_predict(X)                      #ฝึกโมเดลข้อมูลและทำนายกลุ่มข้อมูล

plt.figure(figsize=(10, 6)) # สร้างหน้าต่างกราฟใหม่ ก  ส นิ้ว
plt.gcf().set_facecolor('lightgreen')  #พื้นหลัง
plt.scatter(X[:, 0], X[:, 1], c= Kmean, cmap='viridis')       # 0 แกน X 1 แกน Y คอลัมน์     c กำหนดสีแต่ละจุด
plt.xlabel('Calories Burned' , fontweight='bold')      #แกน x
plt.ylabel('Session Duration (hours)' , fontweight='bold')         # แกน y
plt.title('K-Means Clustering', fontweight='bold')         #  หัวข้อ
plt.show()      # แสดงกราฟ

print("\033[0m\n ______________________________________________________________________________________________________________ \n")

plt.figure(figsize=(10, 6))           # สร้างหน้าต่างกราฟใหม่ ก  ส นิ้ว
plt.gcf().set_facecolor('lightgreen')        #สีพื้นหลังกราฟ

male = data[data['Gender'] == 'Male']           # แสดงจุดเฉพาะของผู้ชาย
plt.scatter(male['Calories_Burned'], male['Session_Duration (hours)'], label='Male', color='blue')  #แสดงข้อมูล ของผู้ชาย สีน้ำเงินและป้ายชื่อ
female = data[data['Gender'] == 'Female']         # แสดงจุดเฉพาะของผู้หญิง
plt.scatter(female['Calories_Burned'], female['Session_Duration (hours)'], label='Female', color='red')  #แสดงข้อมูล ของหญิง สีน้ำแดงและป้ายชื่อ

plt.xlabel('Calories Burned' , fontweight='bold')
plt.ylabel('Session Duration (hours)' , fontweight='bold')
plt.title('Clustering Results: Male vs Female', fontweight='bold')
plt.legend()                                                      #แสดงป้ายชื่อ ข้อมูลข้างบน
plt.show()

avg = data.groupby('Gender')[['Calories_Burned', 'Session_Duration (hours)']].mean()   # แบ่งข้อมูลจาก Gender และหาค่า เฉลี่ยจาก Calories_Burned , Session_Duration
print("\n\033[31mค่าเฉลี่ยการเผาผลาญแคลอรีของผู้หญิงและผู้ชาย:\033[0m")      #แสดงข้อความ
print(avg)      #แสดงข้อมูลของ ชาย หญิง

female_avg_calories = avg.loc['Female', 'Calories_Burned']        #ดึงข้อมูลจากavg  loc เลือกค่า Female ที่อยู่ในแถว ในคอลัมน์   Calories_Burned
male_avg_calories = avg.loc['Male', 'Calories_Burned']           #ดึงข้อมูลจากavg  loc เลือกค่า male ที่อยู่ในแถว ในคอลัมน์   Calories_Burned
if female_avg_calories > male_avg_calories:                                                       #สร้างเงื่อนไข ในการตรวจสอบว่า ถ้า ผู้หญิงมากกว่า จะแสดง
    print("\033[31mผลลัพธ์: ผู้หญิงเผาผลาญแคลอรีมากกว่าผู้ชาย\033[33m")
else:
    print("\033[31mผลลัพธ์: ผู้ชายเผาผลาญแคลอรีมากกว่าผู้หญิง\033[33m")                #สร้างเงื่อนไข ในการตรวจสอบว่า ถ้า ไม่ใช่ผู้ชาย มากกว่าจะแสดง

"""# Data Visualization  Charts

**เลือก Chart ที่ต้องการ Pie  Chart**

* ประเภทของการออกกำลังกาย แบบไหนนิยมมากที่สุด กี่เปอร์เซ็น%
"""

import pandas as pd  # อ่านไฟล์ และแก้ไขไฟล์
import matplotlib.pyplot as plt  # ใช้สำหรับการสร้างกราฟและการแสดงผลข้อมูลในรูปแบบภาพ เช่น Pie Chart

data = pd.read_csv('cleandataGym')  # อ่านข้อมูลจากไฟล์ CSV และโหลดข้อมูลเข้าไปในตัวแปร data (DataFrame)
Workout = data['Workout_Type'].value_counts()    #หาข้อมูลจาก dataframe  ของ ประเภทการออกกำลังกาย

most = Workout.max()  # จำนวนที่มากที่สุด
total = Workout.sum()  # จำนวนทั้งหมด
percent = (most / total) * 100  # คำนวณเปอร์เซ็นต์
print(f"With {most} occurrences, which is {percent:.2f}% of the total workouts.") # แสดงผลเปอร์เซ็นต์ของประเภทที่นิยมมากที่สุด

plt.figure(figsize=(10, 6))  # สร้างหน้าต่างกราฟใหม่ กว้าง 10 นิ้ว สูง 6 นิ้ว
color = ['rosybrown','gold','cyan','cornflowerblue']    # สีที่กำหนด
plt.gcf().set_facecolor('forestgreen')        #สีพื้นหลังกราฟ
Workout.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors = color)

plt.axis('equal')  # ทำให้กราฟเป็นวงกลม
plt.title('Workout Type Distribution', fontsize=18)  # แสดงหัวข้อ ฟอนต์ขนาด 18
plt.tight_layout()  # จัดการตำแหน่งขององค์ประกอบต่าง ๆ ในกราฟให้อยู่ในพื้นที่ที่เหมาะสม
plt.show()  # แสดงกราฟ Pie Chart บนหน้าจอ

"""**จากกราฟ Strength** เป็นที่นิยมมากที่สุด  26.6%

# Data Visualization  Charts

**เลือก Chart ที่ต้องการ Column and Line**

การออกกำลังกายแต่ละแบบเฉลี่ยแล้ว เผาผลาญแคลอรี่เท่าไหร่ ?
"""

import pandas as pd  # อ่านไฟล์ และแก้ไขไฟล์
import matplotlib.pyplot as plt  # ใช้สำหรับการสร้างกราฟและการแสดงผลข้อมูลในรูปแบบภาพ เช่น Pie Chart

data = pd.read_csv('cleandataGym')  # อ่านข้อมูลจากไฟล์ CSV และโหลดข้อมูลเข้าไปในตัวแปร data (DataFrame)
calories = data.groupby('Workout_Type')['Calories_Burned'].mean()      #คำนวณค่าเฉลี่ย ตามประเภทการออก

print("\n\033[31mAverage Calories Burned by Workout Type:\033[0m")  # แสดงค่าแคลอรี่ที่คำนวณออกมา
print(calories.to_string())  #แสดงข้อมูล แต่ละประเภท

fig, ax = plt.subplots(figsize=(10, 6))   # สร้างกราฟ
plt.gcf().set_facecolor('orange')        #สีพื้นหลังกราฟ

ax.bar(calories.index, calories , color='tomato')  # กราฟแท่ง (Column Chart)
ax.plot(calories.index, calories, color='black', marker='o')    # กราฟเส้น (Line Chart)

ax.set_xlabel('Workout Type', fontsize=16 )      # กำหนดชื่อแกน X
ax.set_ylabel('Average Calories Burned', fontsize=16, fontweight='bold')   # กำหนดชื่อแกน Y
ax.set_title('Calories Burned by Workout Type', fontsize=16, fontweight='bold')    # กำหนดชื่อหัวข้อกราฟ
plt.show()

"""จากกราฟ
* Cardio      878.294606 เผาผลาญแคลอรี่

* HIIT        921.393519 เผาผลาญแคลอรี่

*  Strength    909.728745 เผาผลาญแคลอรี่

* Yoga        909.141593 เผาผลาญแคลอรี่
"""